FROM vuejs/ci as build-stage

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY ./vue.config.js /app/vue.config.js
COPY ./babel.config.js /app/babel.config.js
COPY ./src/ /app/src/
COPY ./public/ /app/public/
COPY ./.eslintrc.json /app/.eslintrc.json

RUN npm run build

FROM nginx:stable-alpine as prod
COPY --from=build-stage /app/dist /app
COPY ./vueconfig.conf /etc/nginx/nginx.conf
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]