FROM vuejs/ci as build-stage

RUN mkdir /app
WORKDIR /app

ENV CHOKIDAR_USEPOLLING=true

RUN npm install -g httpserver

COPY package*.json ./

RUN npm install

EXPOSE 8080

CMD ["npm", "run", "serve"]