version: "3"

services:
  client:
    build: 
      context: ./build-a-bot
      dockerfile: Dockerfile.local
    image: vue-learning.client:local
    ports:
      - 8080:8080
    depends_on:
      - api
    restart: unless-stopped
  api:
    build:
      context: ./build-a-bot-server
      dockerfile: Dockerfile.local
    image: vue-learning.server:local
    ports:
      - 8082:8082
    restart: unless-stopped      
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile.local
    image: vue-learing.proxy:local
    ports:
      - 80:80
    depends_on:
      - api
      - client

