version: "3"

services:
  client:
    build: 
      context: ./build-a-bot
      dockerfile: Dockerfile.local
    image: vue-learning.client:local
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
    restart: unless-stopped
  api:
    build:
      context: ./build-a-bot-server
      dockerfile: Dockerfile.local
    image: vue-learning.server:local
    ports:
      - 8080:8080
    restart: unless-stopped      
    
